### ISSUE TITLE
unitfile missing

### ISSUE THREAD

**Issue by stdweird** [ubccr/akrr#12]
AKRR should ship a systemd unitfile (and start/stop the daemon using systemctl commands)
(the rpm post-install script should do systemctl daemon-reload)

**Comment by stdweird** [comment]
i can make a PR if needed, i'm familiar with this

**Comment by nsimakov** [comment]
Dear Stijn,

Thanks for the proposition.

I am not sure is AKRR ready to go with systemctl or the benefits of that step. I only can think of unification with other services.

It was designed to run from regular user space with regular ssh/scp stuff to mimic normal user operation.

I'll talk to other developer on that.
-Nikolay
